Numpy

In [21]:
import numpy as np

array_from_list = np.array([1,2,3,4,5])
print(array_from_list)
type(array_from_list)
print(array_from_list.ndim)
print(array_from_list.shape)


[1 2 3 4 5]
1
(5,)


In [7]:
# array_from_tuple_error = np.array(1,2,3,4,5) // gives error  array() takes from 1 to 2 positional arguments but 5 were given
array_from_tuple = np.array((1,2,3,4,5))
print(array_from_tuple)
type(array_from_tuple)

[1 2 3 4 5]


numpy.ndarray

In [23]:
array_2d = np.array([[1,2,3],
                     [4,5,6],
                     [7,8,9]])
print(array_2d)
print(array_2d.ndim)
print(array_2d.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
(3, 3)


In [29]:
array_3d = np.array([[[1,2,3],
                      [4,5,6],
                      [7,8,9]]])  # 1 block, 3 row, 3 cols
array_3d_1 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])  # 2 block, 2 row, 2 cols

print(array_3d)
print(array_3d.ndim)
print(array_3d.shape)

print(array_3d_1)
print(array_3d_1.ndim)
print(array_3d_1.shape)


[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
3
(1, 3, 3)
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
3
(2, 2, 2)


In [ ]:
array_4d = np.array([[[[1,2,3],
                       [4,5,6],
                       [7,8,9]]]])
array_4d

array([[[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]]])

In [ ]:
array_1 = np.array([1,2,3,'a'])

print(array_1)
print(array_1.dtype) # converts into string/ U11 as it is more feasibe to convert the number into str. Homogeneos type

['1' '2' '3' 'a']
<U11


In [ ]:
array_2 = np.array([2,3,4.3, 5.77])
print(array_2)
print(array_2.dtype) # converted the int into float 

[2.   3.   4.3  5.77]
float64


In [33]:
print("Item size of array_2 ", array_2.itemsize," byte")
# itemsize return the size of each index  , here it's 8 bytes and if we want to know the size of array then multiply it by no.of items * itemsize

print(" size of array_2 ", array_2.itemsize * len(array_2)," byte")

Item size of array_2  8  byte
 size of array_2  32  byte


Indexing and Slicing

In [43]:
print(array_from_list[2])
print(array_2d[0])
print(array_2d[0][2])
print(array_2d[1][2])

print(array_3d[0])
print(array_3d[0][1])
print(array_3d[0][1][2])


print(array_3d_1[1])
print(array_3d_1[1][1])
print(array_3d_1[1][1][0])

3
[1 2 3]
3
6
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[4 5 6]
6
[[5 6]
 [7 8]]
[7 8]
7


In [ ]:
array_from_list[2:4]



array([3, 4])

In [51]:
array_2d[0:2,1:3]

array([[2, 3],
       [5, 6]])

In [52]:
array_2d[1:3, 1:3]

array([[5, 6],
       [8, 9]])

In [62]:
array_3d_2 = np.array([[[1,2,3],[4,5,6]],
                       [[7,8,9],[11,12,13]],
                       [[14,15,16],[98,84,00]]])
array_3d_2

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [11, 12, 13]],

       [[14, 15, 16],
        [98, 84,  0]]])

In [64]:
array_3d_2[0:2, 1 , 1:3]

array([[ 5,  6],
       [12, 13]])