Numpy

In [2]:
import numpy as np

array_from_list = np.array([1,2,3,4,5])
print(array_from_list)
type(array_from_list)
print(array_from_list.ndim)
print(array_from_list.shape)


[1 2 3 4 5]
1
(5,)


In [7]:
# array_from_tuple_error = np.array(1,2,3,4,5) // gives error  array() takes from 1 to 2 positional arguments but 5 were given
array_from_tuple = np.array((1,2,3,4,5))
print(array_from_tuple)
type(array_from_tuple)

[1 2 3 4 5]


numpy.ndarray

In [23]:
array_2d = np.array([[1,2,3],
                     [4,5,6],
                     [7,8,9]])
print(array_2d)
print(array_2d.ndim)
print(array_2d.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
(3, 3)


In [29]:
array_3d = np.array([[[1,2,3],
                      [4,5,6],
                      [7,8,9]]])  # 1 block, 3 row, 3 cols
array_3d_1 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])  # 2 block, 2 row, 2 cols

print(array_3d)
print(array_3d.ndim)
print(array_3d.shape)

print(array_3d_1)
print(array_3d_1.ndim)
print(array_3d_1.shape)


[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
3
(1, 3, 3)
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
3
(2, 2, 2)


In [ ]:
array_4d = np.array([[[[1,2,3],
                       [4,5,6],
                       [7,8,9]]]])
array_4d

array([[[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]]])

In [ ]:
array_1 = np.array([1,2,3,'a'])

print(array_1)
print(array_1.dtype) # converts into string/ U11 as it is more feasibe to convert the number into str. Homogeneos type

['1' '2' '3' 'a']
<U11


In [ ]:
array_2 = np.array([2,3,4.3, 5.77])
print(array_2)
print(array_2.dtype) # converted the int into float 

[2.   3.   4.3  5.77]
float64


In [33]:
print("Item size of array_2 ", array_2.itemsize," byte")
# itemsize return the size of each index  , here it's 8 bytes and if we want to know the size of array then multiply it by no.of items * itemsize

print(" size of array_2 ", array_2.itemsize * len(array_2)," byte")

Item size of array_2  8  byte
 size of array_2  32  byte


Indexing and Slicing

In [43]:
print(array_from_list[2])
print(array_2d[0])
print(array_2d[0][2])
print(array_2d[1][2])

print(array_3d[0])
print(array_3d[0][1])
print(array_3d[0][1][2])


print(array_3d_1[1])
print(array_3d_1[1][1])
print(array_3d_1[1][1][0])

3
[1 2 3]
3
6
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[4 5 6]
6
[[5 6]
 [7 8]]
[7 8]
7


In [ ]:
array_from_list[2:4]



array([3, 4])

In [51]:
array_2d[0:2,1:3]

array([[2, 3],
       [5, 6]])

In [52]:
array_2d[1:3, 1:3]

array([[5, 6],
       [8, 9]])

In [48]:
array_3d_2 = np.array([[[1,2,3],[4,5,6]],
                       [[7,8,9],[11,12,13]],
                       [[14,15,16],[98,84,00]]])
array_3d_2

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [11, 12, 13]],

       [[14, 15, 16],
        [98, 84,  0]]])

In [64]:
array_3d_2[0:2, 1 , 1:3]

array([[ 5,  6],
       [12, 13]])

Arithmetic Operations

In [3]:
a = np.array([[1,2],[3,4]])
b = np.array([[10, 11],[12, 13]])

print(a)
print(b)

[[1 2]
 [3 4]]
[[10 11]
 [12 13]]


In [4]:
print(a + b)

[[11 13]
 [15 17]]


In [5]:
print(a - b)

[[-9 -9]
 [-9 -9]]


In [6]:
print(a * b)

[[10 22]
 [36 52]]


In [7]:
print(a / b)

[[0.1        0.18181818]
 [0.25       0.30769231]]


In [8]:
print(b / a)

[[10.    5.5 ]
 [ 4.    3.25]]


In [10]:
print(a//b)

print(b//a)

[[0 0]
 [0 0]]
[[10  5]
 [ 4  3]]


In [12]:
print(a ** 2)
print(b ** 3)

[[ 1  4]
 [ 9 16]]
[[1000 1331]
 [1728 2197]]


Methods in Numpy

In [26]:
c = np.array([[1,2,3],[4,11,6],[7,8,9]])
c.shape
print(c.transpose())

[[ 1  4  7]
 [ 2 11  8]
 [ 3  6  9]]


In [27]:
m  = np.array([83485,43,54,4,24])
print(np.sort(m))
print(np.sort(c))



[    4    24    43    54 83485]
[[ 1  2  3]
 [ 4  6 11]
 [ 7  8  9]]


In [ ]:
c = np.array([[1,2,3],[4,11,6],[7,8,9]])
c.shape
print(np.sort(c, axis=0))   # sorts cols wise
print(np.sort(c, axis=1))  # sorts row wise

[[ 1  2  3]
 [ 4  8  6]
 [ 7 11  9]]
[[ 1  2  3]
 [ 4  6 11]
 [ 7  8  9]]


In [ ]:
c = np.array([4,3, 34, 77 ,23,45,1,12])
print(np.argsort(c))  #

[6 1 0 7 4 2 5 3]


In [39]:
# Concatenation of Arrays

arr1  = np.array([1,5,3])
arr2 = np.array([45,5,7])

np.concatenate((arr1, arr2))


array([ 1,  5,  3, 45,  5,  7])

In [49]:
# Reshape

array_1 = np.array([1,3,5,6,7,8, 7,0])
array_1.reshape(2,4)

array_3d_2.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13, 14, 15, 16, 98, 84,
        0])

In [50]:
# Split

np.split(array_1,4)

[array([1, 3]), array([5, 6]), array([7, 8]), array([7, 0])]